version: "3"

services:
  nodeos:
    image: eosio/eos:latest
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeos:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --plugin=eosio::chain_api_plugin --plugin=eosio::history_api_plugin --plugin=eosio::net_api_plugin --plugin=eosio::producer_api_plugin --http-validate-host=false --access-control-allow-origin=* --access-control-allow-headers=true --hard-replay
    hostname: nodeos
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - /data/nodeos:/opt/eosio/bin/data-dir
    # cap_add:
    #   - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: eosio/eos:latest
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900 --unlock-timeout=86400 --http-validate-host=false --access-control-allow-origin=* --access-control-allow-headers=true
    hostname: keosd
    ports:
      - 8900:8900
    expose:
      - "8900"
    links:
      - nodeos
    volumes:
      - /data/keosd:/opt/eosio/bin/data-dir
      - /data/eosio-wallet:/root/eosio-wallet
    stop_grace_period: 10m
